@set allusersprofile=c:\programdata
@set appdata=c:\users\aleksei goliguzov\appdata\roaming
@set asl.log=destination=file
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-kcvolii
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=d:\program files (x86)\microsoft visual studio\2017\community\common7\ide\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft sdks\f#\4.1\framework\v4.0\
@set homedrive=c:
@set homepath=\users\aleksei goliguzov
@set ifcpath=d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\ifc\x86
@set include=d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\atlmfc\include;d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\include;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\10\include\10.0.16299.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.16299.0\shared;c:\program files (x86)\windows kits\10\include\10.0.16299.0\um;c:\program files (x86)\windows kits\10\include\10.0.16299.0\winrt
@set lib=d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\atlmfc\lib\x86;d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\lib\x86;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x86;c:\program files (x86)\windows kits\10\lib\10.0.16299.0\ucrt\x86;c:\program files (x86)\windows kits\10\lib\10.0.16299.0\um\x86
@set libpath=d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\atlmfc\lib\x86;d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\lib\x86;d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.16299.0;c:\program files (x86)\windows kits\10\references\10.0.16299.0;c:\windows\microsoft.net\framework\v4.0.30319
@set localappdata=c:\users\aleksei goliguzov\appdata\local
@set logonserver=\\desktop-kcvolii
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=d:\program files (x86)\microsoft visual studio\2017\community\msbuild\sdks
@set msbuild_exe_path=d:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=4
@set onedrive=c:\users\aleksei goliguzov\onedrive
@set os=windows_nt
@set path=d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\bin\hostx86\x86;d:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft sdks\typescript\2.5;d:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\testwindow;d:\program files (x86)\microsoft visual studio\2017\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;d:\program files (x86)\microsoft visual studio\2017\community\msbuild\15.0\bin\roslyn;d:\program files (x86)\microsoft visual studio\2017\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;c:\program files (x86)\microsoft sdks\f#\4.1\framework\v4.0\;c:\program files (x86)\windows kits\10\bin\x86;c:\program files (x86)\windows kits\10\bin\10.0.16299.0\x86;d:\program files (x86)\microsoft visual studio\2017\community\\msbuild\15.0\bin;c:\windows\microsoft.net\framework\v4.0.30319;d:\program files (x86)\microsoft visual studio\2017\community\common7\ide\;d:\program files (x86)\microsoft visual studio\2017\community\common7\tools\;c:\program files (x86)\iis express\php\v7.1;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\dotnet\;d:\lib\opencv\build\x64\vc15\bin;d:\lib\opencv\build\x64\vc14\bin;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\xoreax\incredibuild;c:\users\aleksei goliguzov\appdata\local\microsoft\windowsapps;c:\users\aleksei goliguzov\appdata\local\githubdesktop\bin;c:\users\aleksei goliguzov\appdata\local\microsoft\windowsapps;c:\users\aleksei goliguzov\appdata\local\githubdesktop\bin;d:\lib\opencv\build\x64\vc14\bin;d:\lib\opencv\build\x64\vc15\bin
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set phpvs_pid=8920
@set pkgdefapplicationconfigfile=c:\users\aleksei goliguzov\appdata\local\microsoft\visualstudio\15.0_4456816a\devenv.exe.config
@set platform=x86
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 58 stepping 9, genuineintel
@set processor_level=6
@set processor_revision=3a09
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=d:\program files (x86)\microsoft visual studio\2017\community\msbuild
@set pvs_vsinstalldir=d:\program files (x86)\microsoft visual studio\2017\community
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\alekse~1\appdata\local\temp
@set tmp=c:\users\alekse~1\appdata\local\temp
@set ucrtversion=10.0.16299.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-kcvolii
@set userdomain_roamingprofile=desktop-kcvolii
@set username=aleksei goliguzov
@set userprofile=c:\users\aleksei goliguzov
@set vcideinstalldir=d:\program files (x86)\microsoft visual studio\2017\community\common7\ide\vc\
@set vcinstalldir=d:\program files (x86)\microsoft visual studio\2017\community\vc\
@set vctoolsinstalldir=d:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.12.25827\
@set vctoolsredistdir=d:\program files (x86)\microsoft visual studio\2017\community\vc\redist\msvc\14.12.25810\
@set vctoolsversion=14.12.25827
@set visualstudiodir=d:\aleksei goliguzov\documents\visual studio 2017
@set visualstudioedition=microsoft visual studio community 2017
@set visualstudioversion=15.0
@set vs150comntools=d:\program files (x86)\microsoft visual studio\2017\community\common7\tools\
@set vsappiddir=d:\program files (x86)\microsoft visual studio\2017\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x86
@set vscmd_arg_tgt_arch=x86
@set vscmd_ver=15.5.5
@set vsinstalldir=d:\program files (x86)\microsoft visual studio\2017\community\
@set vslang=1049
@set vsskuedition=community
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.16299.0;c:\program files (x86)\windows kits\10\references\10.0.16299.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.16299.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.16299.0\
@set windowssdkversion=10.0.16299.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set __dotnet_add_32bit=1
@set __dotnet_preferred_bitness=32
@set __vscmd_preinit_path=c:\program files (x86)\iis express\php\v7.1;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\dotnet\;d:\lib\opencv\build\x64\vc15\bin;d:\lib\opencv\build\x64\vc14\bin;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\xoreax\incredibuild;c:\users\aleksei goliguzov\appdata\local\microsoft\windowsapps;c:\users\aleksei goliguzov\appdata\local\githubdesktop\bin;c:\users\aleksei goliguzov\appdata\local\microsoft\windowsapps;c:\users\aleksei goliguzov\appdata\local\githubdesktop\bin;d:\lib\opencv\build\x64\vc14\bin;d:\lib\opencv\build\x64\vc15\bin

@call cl.exe